encoding: utf-8
title: Dreamore-不老歌
description: > # this means to ignore newlines until "baseurl:"
 在这里，开始你们的伟大冒险
permalink: pretty
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://HaoXiangDreamore.com" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: 陈小耗 # add your name
author-img: haozi.jpg # add your photo
about-author: # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
